version: "3.8"
services:
  langchain:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-west-2
      - ALLOW_ORIGINS=*
      - SAGEMAKER_ENDPOINT_NAME=Rinna-Inference
      - CALM_ENDPOINT_NAME=Open-calm-7b-ft3
      - KENDRA_INDEX_ID=299292dd-9702-4909-ab48-eda8d4049a67
      - ANTHROPIC_API_KEY=
      - LLM=rinna
    networks:
      - public
      - private
networks:
  public:
  private: