version: "3.8"
services:
  langchain:
    build:
      context: ./langchain
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=us-west-2
      - AWS_BEDROCK_REGION=us-east-1
      - ALLOW_ORIGINS=*
      - SAGEMAKER_ENDPOINT_NAME=Rinna-Inference
      - LLM=claude_bedrock
    secrets:
      - KENDRA_INDEX_ID
      # - ANTHROPIC_API_KEY
    networks:
      - private
networks:
  public:
  private:
secrets:
  KENDRA_INDEX_ID:
    file: ../secrets/.secret-kendra
  # ANTHROPIC_API_KEY:
  #   file: ../secrets/.secret-anthropic